src/Entity/Commentaire.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentaireRepository")
 */
class Commentaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="commentaires")
     */
    private $User;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Room", inversedBy="commentaires")
     * @ORM\JoinColumn(nullable=false)
     */
    private $room;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getRoom(): ?Room
    {
        return $this->room;
    }

    public function setRoom(?Room $room): self
    {
        $this->room = $room;

        return $this;
    }
}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Entity\User;
/**
 * @ORM\Entity(repositoryClass="App\Repository\ReservationRepository")
 */
class Reservation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_fin;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Client", inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $confirmed;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Room", inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $room;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRoom(): ?Room
    {
        return $this->room;
    }

    public function setRoom(Room $room): self
    {
        $this->room = $room;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getConfirmed(): ?bool
    {
        return $this->confirmed;
    }

    public function setConfirmed(bool $confirmed): self
    {
        $this->confirmed = $confirmed;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_debut')
            ->add('date_fin')
            ->add('room')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use App\Entity\User;
use App\Entity\Client;
use App\Entity\Unavaibility;
use App\Form\UnavaibilityType;
use App\Repository\UnavaibilityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/reservation")
 */
class ReservationController extends AbstractController
{    
    
    /**
     * @Route("/", name="reservation_index", methods={"GET"})
     */
    public function index(ReservationRepository $reservationRepository): Response
    {
//         if (!is_object($this->getUser())) {
//             $user_id = null;
//         }
//         else {
//             $user_id = $this->getUser()->getId();
//         }
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(), 'sous_titre' => "Vos réservations",
        ]);
    }

    /**
     * @Route("/new", name="reservation_new", methods={"GET","POST"})
     */
    public function new(Request $request, ReservationRepository $reservationRepository): Response
    {
        $user = $this->getUser();
        $reservation = new Reservation();
        if ($user == null){
            return $this->redirectToRoute('login');
            
        }
        $reservation->setClient($this->getUser()->getClient());
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);
        /* On sécurise le formulaire en vérifiant qu'il a bien le droit de modifier */
        if ($form->isSubmitted() && $form->isValid()) {
            /* On va regarder si la réservation est compatible avec les réservations déjà faites pour la chambre */
            /* Condition de segments gauche->droite */
            $cond1 = $reservation->getDateDebut() <= $reservation->getDateFin();
            if(!$cond1){
                $this->get('session')->getFlashBag()->add('error', 'La date de début doit être avant la date de fin.');
                return $this->redirectToRoute('reservation_index');
                
            }
            $reservations = $reservationRepository->findBy(['room' => $reservation->getRoom()]);
            foreach ($reservations as $res){
                /* Conditions de non intersection de deux segments de type [i,j] où j>=i */
                $ou1 = $reservation->getDateDebut() <= $res->getDateDebut() && $reservation->getDateFin() <= $res->getDateDebut();
                $ou2 = $reservation->getDateDebut() >= $res->getDateFin();
                $ou = $ou1 || $ou2;
                if (! $ou) {
                    $this->get('session')->getFlashBag()->add('error', 'La chambre est déjà prise à cette date, veuillez choisir une autre date.');
                    return $this->redirectToRoute('reservation_index');
                }
            }
            $unavaibilities = $reservationRepository->findBy(['room' => $reservation->getRoom()]);
            foreach ($unavaibilities as $unaiv){
                /* Conditions de non intersection de deux segments de type [i,j] où j>=i */
                $ou1 = $reservation->getDateDebut() <= $unaiv->getDateDebut() && $reservation->getDateFin() <= $unaiv->getDateDebut();
                $ou2 = $reservation->getDateDebut() >= $unaiv->getDateFin();
                $ou = $ou1 || $ou2;
                if (! $ou) {
                    $this->get('session')->getFlashBag()->add('error', 'La chambre est déjà prise à cette date, veuillez choisir une autre date.');
                    return $this->redirectToRoute('reservation_index');
                }
            }
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('reservation_index');
        }

        return $this->render('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),'sous_titre' => "Ajouter une réservation",
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_show", methods={"GET"})
     */
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reservation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reservation $reservation, ReservationRepository $reservationRepository): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);
        $user = $this->getUser();
        if ($user != null && $user== $reservation->getClient()->getUser() && $form->isSubmitted() && $form->isValid()) {
            /* On va regarder si la réservation est compatible avec les réservations déjà faites pour la chambre */
            /* Condition de segments gauche->droite */
            $cond1 = $reservation->getDateDebut() <= $reservation->getDateFin();
            if(!$cond1){
                $this->get('session')->getFlashBag()->add('error', 'La date de début doit être avant la date de fin.');
                return $this->redirectToRoute('reservation_index');
                
            }
            $reservations = $reservationRepository->findBy(['room' => $reservation->getRoom()]);
            foreach ($reservations as $res){
                /* Conditions de non intersection de deux segments de type [i,j] où j>=i */
                $ou1 = $reservation->getDateDebut() <= $res->getDateDebut() && $reservation->getDateFin() <= $res->getDateDebut();
                $ou2 = $reservation->getDateDebut() >= $res->getDateFin();
                $ou = $ou1 || $ou2;
                if (! $ou) {
                    $this->get('session')->getFlashBag()->add('error', 'La chambre est déjà prise à cette date, veuillez choisir une autre date.');
                    return $this->redirectToRoute('reservation_index');
                }
            }
            
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reservation_index');
        }

        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Reservation $reservation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reservation_index');
    }
}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block main %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('reservation_index') }}">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation index{% endblock %}

{% block main %}

    <h1>Reservation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Chambre</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% if app.user == null %}
        	    <tr>
                    <td colspan="4">no records found</td>
                </tr>
        	
        {% elseif is_granted('ROLE_ADMIN') %}
            {% for reservation in reservations %}
                <tr>
                    <td>{{ reservation.room.summary }}</td>
                    <td>{{ reservation.dateDebut ? reservation.dateDebut|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ reservation.dateFin ? reservation.dateFin|date('Y-m-d H:i:s') : '' }}</td>
                    <td>
                        <a href="{{ path('reservation_show', {'id': reservation.id}) }}">voir</a>
                        <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">modifier</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
        {% else %}
            {% for reservation in reservations %}
            	{% if reservation.room.owner.user == app.user %}
                    <tr>
                        <td>{{ reservation.room.summary }}</td>
                        <td>{{ reservation.dateDebut ? reservation.dateDebut|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ reservation.dateFin ? reservation.dateFin|date('Y-m-d H:i:s') : '' }}</td>
                        <td>
                            <a href="{{ path('reservation_show', {'id': reservation.id}) }}">voir</a>
                            <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">modifier</a>
                        </td>
                    </tr> 
                 {% elseif reservation.client.user == app.user %}     
                    <tr>
                        <td>{{ reservation.room.summary }}</td>
                        <td>{{ reservation.dateDebut ? reservation.dateDebut|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ reservation.dateFin ? reservation.dateFin|date('Y-m-d H:i:s') : '' }}</td>
                        <td>
                            <a href="{{ path('reservation_show', {'id': reservation.id}) }}">voir</a>
                            <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">modifier</a>
                            
                        </td>
                    </tr> 
                           
                {% endif %}
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
        	
        {% endif %}
        </tbody>
    </table>

     <a href="{{ path('reservation_new') }}">Create new</a>
     <a href="{{ path('unavaibility_index') }}">Voir indisponibilités</a>
    </section>
</div>
{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block main %}
    <h1>Create new Reservation</h1>

    {{ include('reservation/_form.html.twig') }}

    <a href="{{ path('reservation_index') }}">back to list</a>
{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block main %}
    <h1>Reservation</h1>
    <table class="table">
        <tbody>
            <tr>
                <th>Chambre</th>
                <td>{{ reservation.room.summary }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ reservation.dateDebut ? reservation.dateDebut|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ reservation.dateFin ? reservation.dateFin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('reservation_index') }}">Retour à mes réservations</a>

    <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">modifier</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}